version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: tasks_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-secret-key-for-development
      - DATABASE_URL=postgresql://tasks_user:tasks_password@db:5432/tasks_db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  # worker:
  #   build: .
  #   command: celery -A core worker --loglevel=info
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DEBUG=True
  #     - SECRET_KEY=django-secret-key-for-development
  #     - DATABASE_URL=postgresql://tasks_user:tasks_password@db:5432/tasks_db
  #     - REDIS_URL=redis://redis:6379/1
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres_data: